/*
Project: Customer Retention Analytics
Script: 04_customer_lifetime_value.sql
Goal: Calculate Customer Lifetime Value (CLV) for each customer.

Description:
This query calculates the total revenue generated by each customer
throughout their purchase history. It first calculates the total
value of each order, then aggregates order data at the customer level
to compute total orders, total revenue, and average order value.
*/

WITH order_values AS (
SELECT
    CustomerKey,
    SalesOrderNumber,
    SUM(SalesAmount) AS order_value   -- calculate total value for each order
FROM FactInternetSales
GROUP BY
    CustomerKey,
    SalesOrderNumber
),

customer_metrics AS (
SELECT
    CustomerKey,
    COUNT(SalesOrderNumber) AS total_orders,   -- count total orders per customer
    SUM(order_value) AS total_revenue,   -- calculate total revenue generated by the customer
    AVG(order_value) AS avg_order_value   -- compute average value per order
FROM order_values
GROUP BY
    CustomerKey
)

SELECT
    cm.CustomerKey,
    dc.FirstName + ' ' + dc.LastName AS customer_name,   -- retrieve customer full name
    cm.total_orders,
    cm.total_revenue,
    ROUND(cm.avg_order_value, 2) AS avg_order_value,
    cm.total_revenue AS customer_lifetime_value   -- total revenue represents CLV
FROM customer_metrics cm
JOIN DimCustomer dc
    ON cm.CustomerKey = dc.CustomerKey   -- join to get customer details
ORDER BY
    customer_lifetime_value DESC;   -- highest value customers first
