/*
Project: Customer Retention Analytics
Script: 05_customer_revenue_segmentation.sql
Goal: Segment customers based on revenue contribution.

Description:
This query calculates the total revenue generated by each customer
and divides customers into four revenue groups using the NTILE
window function. Customers with the highest revenue are placed
in the top segment, helping identify the most valuable customers.
*/

WITH customer_revenue AS (
SELECT
    CustomerKey,
    SUM(SalesAmount) AS total_revenue   -- calculate total revenue generated by each customer
FROM FactInternetSales
GROUP BY
    CustomerKey
),

revenue_segmenting AS (
SELECT
    cr.CustomerKey,
    dc.FirstName + ' ' + dc.LastName AS customer_name,   -- retrieve customer full name from dimension table
    cr.total_revenue,
    NTILE(4) OVER (ORDER BY cr.total_revenue DESC) AS revenue_segment   -- divide customers into 4 revenue tiers
FROM customer_revenue cr
JOIN DimCustomer dc
    ON cr.CustomerKey = dc.CustomerKey   -- join to retrieve customer details
)

SELECT
    CustomerKey,
    customer_name,
    total_revenue,
    revenue_segment,
    CASE
        WHEN revenue_segment = 1 THEN 'High Value'
        WHEN revenue_segment = 2 THEN 'Medium Value'
        WHEN revenue_segment = 3 THEN 'Low Value'
        ELSE 'Very Low Value'
    END AS revenue_category   -- assign descriptive labels to revenue segments
FROM revenue_segmenting
ORDER BY
    revenue_segment,
    total_revenue DESC;   -- highest revenue customers appear first
